#!/bin/sh /etc/rc.common
# Copyright (C) 2023 Dengfeng Liu
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

USE_PROCD=1
START=99

CONF="chatgptd"
PROG="/usr/bin/chatgptd"

start_service() {
    config load "$CONF"

	local enabled
	config_get_bool enabled "config" "enabled"
	[ "$enabled" -eq "1" ] || return 1

	procd_open_instance
	procd_set_param command "$PROG" -c "$conf_file" -f -d $loglevel
	procd_set_param file "$conf_file"
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}