#!/bin/sh /etc/rc.common
# Copyright (C) 2023 Dengfeng Liu

USE_PROCD=1
START=99

CONF="chatgptd"
PROG="/usr/bin/chatgptd"

start_service() {
    config load "$CONF"

    local enabled
	config_get_bool enabled "config" "enabled"
	[ "$enabled" -eq "1" ] || return 1

    procd_open_instance "$CONF"
	procd_set_param command "$PROG"

	procd_append_param command "run"

	procd_set_param respawn
	procd_set_param stderr 1

	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}