#!/bin/sh

# Copyright (C) 2021 OpenWrt.org

blkdev=`dirname $DEVPATH`
basename=`basename $blkdev`
device=`basename $DEVPATH`
path=$DEVPATH

if [ $basename != "block" ] && [ -z "${device##sd*}" ]; then
        islabel=`block info /dev/$device | grep -q LABEL ; echo $?`
        if [ $islabel -eq 0 ] ; then
                mntpnt=`block info /dev/$device |sed 's/.*LABEL="\([^"]*\)".*/\1/'`
        else
                mntpnt=$device
        fi

        # Do not tolerate spaces in mount points -- the remove case mountpoint determination fails
        if echo "$mntpnt" |grep -q ' ' ; then
                exit 0
        fi

        case "$ACTION" in
                add)
                        mkdir -p "/mnt/$mntpnt"
                        # Set APM value for automatic spin down
                        /sbin/hdparm -B 127 /dev/$device
                        # Try to be gentle on solid state devices
                        mount -o noatime,discard /dev/$device "/mnt/$mntpnt"
                ;;
                remove)
                        # Once the device is removed, the /dev entry disappear. We need mountpoint
                        mountpoint=`mount |grep /dev/$device | sed 's/.* on \(.*\) type.*/\1/'`
                        umount -l $mountpoint
                        rmdir $mountpoint
                ;;
        esac
fi