config server 'main'
    option enabled '0'
    option server_addr '127.0.0.1'
    option server_port '8001'
    option ws_path '/ws/wifidogx'
    option use_ssl '0'
    option token ''
    option device_id ''
    option heartbeat_interval '60'
    option log_level 'info'
