#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99

USE_PROCD=1
PROG=/usr/bin/go-snmp-agentx

start_service() {
	# 加载 snmpd 配置中的 agentxsocket
	config_load snmpd
	local socket
	config_get socket snmpd agentxsocket '/var/run/agentx.sock'

	config_load agentx
	local host port interval
	config_get host trap host ''
	config_get port trap port '162'
	config_get trap_interval trap trap_interval '600'
	config_get check_interval trap check_interval '30'

	procd_open_instance
	procd_set_param reload_signal USR1

	if [ "$host" == '' ]; then
		procd_set_param command $PROG --socket "$socket"
	else
		procd_set_param command $PROG \
			--socket "$socket" \
			--trapServer "$host" \
			--trapPort "$port" \
			--trapInterval "$trap_interval" \
			--checkInterval "$check_interval"
	fi

	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger 'agentx' 'snmpd'
}
